//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangGia()
        {
            this.ChiTietBangGias = new HashSet<ChiTietBangGia>();
        }
    
        public string MaBangGia { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayApDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBangGia> ChiTietBangGias { get; set; }
    }
}
