//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhapTra
    {
        public string MaHH { get; set; }
        public string MaPhieu { get; set; }
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public double DonGia { get; set; }
        public short SoLuong { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual PhieuNhapTra PhieuNhapTra { get; set; }
    }
}
