//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThongKe
    {
        public string MaHD { get; set; }
        public Nullable<double> GiaTri { get; set; }
        public string MaTKDT { get; set; }
    
        public virtual ThongKeDoanhThu ThongKeDoanhThu { get; set; }
    }
}
