//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangTapHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.ChiTietBangGias = new HashSet<ChiTietBangGia>();
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ChiTietPhieuNhapTras = new HashSet<ChiTietPhieuNhapTra>();
        }
    
        public string MaHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public short SoLuong { get; set; }
        public double GiaVon { get; set; }
        public double GiaBan { get; set; }
        public bool TinhTrang { get; set; }
        public string AnhMoTa { get; set; }
        public string MaDVT { get; set; }
        public decimal MucThue { get; set; }
        public string MaThue { get; set; }
        public string MaNhaCungCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBangGia> ChiTietBangGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapTra> ChiTietPhieuNhapTras { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Thue Thue { get; set; }
    }
}
